import { describe, expect, it } from 'vitest'
import { cohortPercentile, deriveAthleteReport, latestStandardsVersion, reportToCsv, resolveReportVersion } from './report'
import { SYNTHETIC_ATHLETES, SYNTHETIC_MEASUREMENTS, SYNTHETIC_SESSIONS } from './seed'
import { STARTER_STANDARDS } from './standards'

describe('report derivation', () => {
  it('derives exactly one athlete, sums grades, and identifies the pinned profile and version', () => { const athlete = SYNTHETIC_ATHLETES[0]; const report = deriveAthleteReport(athlete, SYNTHETIC_SESSIONS, SYNTHETIC_MEASUREMENTS, STARTER_STANDARDS); expect(report.athlete.id).toBe(athlete.id); expect(report.scores.every((score) => SYNTHETIC_MEASUREMENTS.some((m) => m.athleteId === athlete.id && m.metricId === score.metric.id && m.selectedAttempt === score.value))).toBe(true); expect(report.overall).toBe(report.scores.reduce((sum, score) => sum + score.points, 0)); expect(report.maxPoints).toBe(20); expect(report.profile.id).toBe('profile-male'); expect(report.version.version).toBe('1.0.0'); expect(reportToCsv(report)).toContain('standards_profile') })
  it('resolves the exact standards version attached to the latest published session', () => { const newer = { ...structuredClone(STARTER_STANDARDS), id: 'v2', version: '2.0.0' }; const sessions = SYNTHETIC_SESSIONS.map((session) => session.id === 'session-complete' ? { ...session, standardsVersionId: newer.id } : session); expect(resolveReportVersion('ath-a', sessions, [STARTER_STANDARDS, newer])?.version).toBe('2.0.0') })
  it('refuses to silently replace a missing pinned standards profile', () => { const athlete = SYNTHETIC_ATHLETES[0]; const session = { ...SYNTHETIC_SESSIONS[0], profileIdsByAthlete: { ...SYNTHETIC_SESSIONS[0].profileIdsByAthlete, [athlete.id]: 'missing-profile' } }; expect(() => deriveAthleteReport(athlete, [session], SYNTHETIC_MEASUREMENTS, STARTER_STANDARDS)).toThrow('Pinned standards profile') })
  it('computes empirical percentiles in the correct direction and handles ties', () => { expect(cohortPercentile(30, [20, 30, 40], 'higher')).toBe(50); expect(cohortPercentile(4.8, [4.5, 4.8, 5.2], 'lower')).toBe(50); expect(cohortPercentile(10, [10], 'higher')).toBeNull() })
  it('derives percentiles only from published peers pinned to the same profile and version', () => { const athlete = SYNTHETIC_ATHLETES[0]; const report = deriveAthleteReport(athlete, SYNTHETIC_SESSIONS, SYNTHETIC_MEASUREMENTS, STARTER_STANDARDS, SYNTHETIC_ATHLETES); expect(report.scores.every((score) => score.percentile === undefined || score.cohortSize! >= 2)).toBe(true); const foreignProfileSessions = SYNTHETIC_SESSIONS.map((session) => ({ ...session, profileIdsByAthlete: Object.fromEntries(session.athleteIds.map((id) => [id, id === athlete.id ? 'profile-male' : 'profile-female'])) })); const isolated = deriveAthleteReport(athlete, foreignProfileSessions, SYNTHETIC_MEASUREMENTS, STARTER_STANDARDS, SYNTHETIC_ATHLETES); expect(isolated.scores.every((score) => score.percentile === undefined)).toBe(true) })
  it('orders same-day standards versions numerically after repeated revisions', () => { const nine = { ...STARTER_STANDARDS, id: 'nine', version: '1.0.9' }; const ten = { ...STARTER_STANDARDS, id: 'ten', version: '1.0.10' }; expect(latestStandardsVersion([nine, ten])?.id).toBe('ten') })
})
