import { expect, test } from '@playwright/test'

test('real routes, deep links, history, and navigation work', async ({ page }) => {
  await page.goto('/athletes/ath-a')
  await expect(page.getByRole('heading', { name: 'Jordan Ellis', level: 1 })).toBeVisible()
  await page.reload()
  await expect(page).toHaveURL(/\/athletes\/ath-a$/)
  if ((page.viewportSize()?.width ?? 1000) <= 800) await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Testing' }).click()
  await expect(page).toHaveURL(/\/testing$/)
  await page.goBack()
  await expect(page).toHaveURL(/\/athletes\/ath-a$/)
})

test('live result autosaves to IndexedDB and survives reload', async ({ page }) => {
  await page.goto('/testing/session-draft/live')
  const input = page.getByLabel('Countermovement Vertical Jump attempt 1')
  await input.fill('24.5')
  await page.waitForTimeout(100)
  await page.reload()
  await expect(input).toHaveValue('24.5')
})

test('required pages have no viewport overflow', async ({ page }, testInfo) => {
  const routes = ['/', '/athletes', '/testing', '/testing/new', '/testing/session-draft/live', '/testing/session-complete/review', '/database', '/standards', '/reporting', '/reporting/ath-a']
  for (const route of routes) {
    await page.goto(route)
    await expect(page.locator('body')).toBeVisible()
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1)
    expect(overflow, `horizontal overflow at ${route}`).toBe(false)
  }
  await page.goto('/testing/session-draft/live')
  await page.screenshot({ path: `screenshots/live-${testInfo.project.name}.png`, fullPage: true })
  await page.goto('/')
  await page.screenshot({ path: `screenshots/dashboard-${testInfo.project.name}.png`, fullPage: true })
  await page.goto('/standards')
  await page.getByRole('button', { name: /Create version/ }).click()
  await expect(page.getByRole('heading', { name: 'Create scoring version' })).toBeVisible()
  const editorOverflow = await page.locator('.standards-modal').evaluate((element) => element.scrollWidth > element.clientWidth + 1)
  expect(editorOverflow, 'standards editor overflow').toBe(false)
  await page.screenshot({ path: `screenshots/standards-editor-${testInfo.project.name}.png` })
})

test('complete coach workflow creates, captures, publishes, locks, and reports one athlete', async ({ page }) => {
  await page.goto('/testing/new')
  await page.getByPlaceholder('Example: Fall baseline').fill('Acceptance Session')
  await expect(page.getByText('5 selected')).toBeVisible()
  await page.getByRole('button', { name: /Jordan Ellis/ }).click()
  await page.getByRole('button', { name: /Open live intake/ }).click()
  await expect(page).toHaveURL(/\/testing\/[^/]+\/live$/)
  await page.getByLabel('Countermovement Vertical Jump attempt 1').fill('24')
  await page.getByRole('tab', { name: /Broad jump/ }).click()
  await page.getByLabel('Standing Broad Jump attempt 1').fill('96')
  await page.getByRole('tab', { name: /10 yard/ }).click()
  await page.getByLabel('10 Yard Sprint attempt 1').fill('1.8')
  await page.getByRole('tab', { name: /Pro agility/ }).click()
  await page.getByLabel('5-10-5 Pro Agility attempt 1').fill('4.7')
  await page.getByRole('tab', { name: /Bench reps/ }).click()
  await page.getByLabel('Bench Press Repetitions attempt 1').fill('12')
  await page.getByRole('button', { name: /Review session/ }).click()
  await expect(page.getByText('5 / 5')).toBeVisible()
  const benchStatus = page.getByLabel('Jordan Ellis Bench Press Repetitions status')
  await benchStatus.selectOption('excluded')
  await expect(page.getByRole('button', { name: /Approve and publish/ })).toBeDisabled()
  await benchStatus.selectOption('valid')
  await page.getByRole('button', { name: /Approve and publish/ }).click()
  await expect(page.getByText('Published locally.')).toBeVisible()
  await page.getByRole('link', { name: /Open/ }).click()
  await expect(page.getByRole('heading', { name: 'Jordan Ellis', level: 1 })).toBeVisible()
  await expect(page.locator('.report-meta').getByText(/v1.0.0/)).toBeVisible()
  await page.goto((await page.url()).replace(/\/reporting\/ath-a$/, '/testing'))
  await page.locator('article').filter({ hasText: 'Acceptance Session' }).getByRole('link', { name: /View published session/ }).click()
  await page.goto((await page.url()).replace(/\/review$/, '/live'))
  await expect(page.getByText(/published and locked/i)).toBeVisible()
})

test('review state, invalid values, clearing, and queue movement persist correctly', async ({ page }) => {
  await page.goto('/testing/session-draft/live')
  const jump = page.getByLabel('Countermovement Vertical Jump attempt 1')
  await jump.fill('999')
  await expect(page.getByText('Check this value.')).toBeVisible()
  await page.reload()
  await expect(jump).toHaveValue('999')
  await page.getByRole('button', { name: /Clear result/ }).click()
  await expect(jump).toHaveValue('')
  await page.getByRole('button', { name: /Next athlete/ }).click()
  await expect(page.getByText('Taylor Kim', { exact: true }).last()).toBeVisible()
  await page.getByRole('button', { name: /Review session/ }).click()
  await expect(page).toHaveURL(/\/testing\/session-draft\/review$/)
  await page.goto('/testing')
  await expect(page.locator('article').filter({ hasText: 'Synthetic Return Testing' }).getByRole('link', { name: /Continue review/ })).toBeVisible()
})

test('roster creation blocks duplicates and search and filters use the saved record', async ({ page }) => {
  await page.goto('/athletes')
  await page.getByRole('button', { name: /Add athlete/ }).click()
  const addDialog = page.getByRole('dialog')
  await addDialog.getByLabel('First name').fill('Jordan')
  await addDialog.getByLabel('Last name').fill('Ellis')
  await addDialog.getByRole('textbox', { name: 'Sport', exact: true }).fill('Football')
  await addDialog.getByRole('textbox', { name: 'Group', exact: true }).fill('Varsity')
  await addDialog.getByRole('button', { name: 'Add athlete', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('already exists')
  await addDialog.getByLabel('First name').fill('Morgan')
  await addDialog.getByLabel('Last name').fill('Blake')
  await addDialog.getByRole('textbox', { name: 'Sport', exact: true }).fill('Soccer')
  await addDialog.getByLabel('Position').fill('Forward')
  await addDialog.getByRole('textbox', { name: 'Group', exact: true }).fill('Varsity')
  await addDialog.getByRole('button', { name: 'Add athlete', exact: true }).click()
  await page.getByLabel('Search athletes').fill('Morgan')
  await expect(page.getByRole('heading', { name: 'Morgan Blake' })).toBeVisible()
  await page.getByLabel('Search athletes').fill('')
  await page.locator('.filter-bar label').filter({ hasText: 'Sport' }).getByRole('combobox').selectOption('Soccer')
  await expect(page.getByText('athletes').last()).toContainText('2 athletes')
})

test('CSV mapping imports valid rows, preserves errors, and all data downloads fire', async ({ page }) => {
  await page.goto('/database')
  const templateDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: /Download template/ }).click()
  expect((await templateDownload).suggestedFilename()).toBe('fieldhouse-athlete-template.csv')

  await page.locator('input[type="file"][accept*="csv"]').setInputFiles({
    name: 'mapped-roster.csv',
    mimeType: 'text/csv',
    buffer: Buffer.from('given,family,activity,pos,squad\nMorgan,Blake,Soccer,Forward,Varsity\nJordan,Ellis,Football,Quarterback,Varsity\nNoGroup,Person,Soccer,Forward,')
  })
  await page.getByLabel('Map first_name').selectOption('given')
  await page.getByLabel('Map last_name').selectOption('family')
  await expect(page.getByText('1 valid · 2 with errors')).toBeVisible()
  await expect(page.getByText(/already exists/)).toBeVisible()
  await expect(page.getByText(/Group is required/)).toBeVisible()
  await page.getByRole('button', { name: /Import 1 valid row/ }).click()
  await expect(page.getByRole('button', { name: /Valid rows imported/ })).toBeDisabled()
  await expect(page.getByText('mapped-roster.csv').last()).toBeVisible()

  const rosterDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: /Export roster CSV/ }).click()
  expect((await rosterDownload).suggestedFilename()).toBe('fieldhouse-athletes.csv')
  const backupDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: /Export full backup/ }).click()
  expect((await backupDownload).suggestedFilename()).toMatch(/^fieldhouse-backup-\d{4}-\d{2}-\d{2}\.json$/)
})

test('backup round trip restores data and reset returns the synthetic demo', async ({ page }, testInfo) => {
  await page.goto('/athletes')
  await page.getByRole('button', { name: /Add athlete/ }).click()
  const backupDialog = page.getByRole('dialog')
  await backupDialog.getByLabel('First name').fill('Backup')
  await backupDialog.getByLabel('Last name').fill('Proof')
  await backupDialog.getByRole('textbox', { name: 'Sport', exact: true }).fill('Track')
  await backupDialog.getByRole('textbox', { name: 'Group', exact: true }).fill('Test')
  await backupDialog.getByRole('button', { name: 'Add athlete', exact: true }).click()
  await expect(page.locator('.result-count')).toHaveText('7 athletes')
  await page.goto('/database')
  const backupEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: /Export full backup/ }).click()
  const backup = await backupEvent
  const backupPath = testInfo.outputPath('fieldhouse-round-trip.json')
  await backup.saveAs(backupPath)

  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: /Reset demo data/ }).click()
  await expect(page.getByText('6 athletes').first()).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*="json"]').setInputFiles(backupPath)
  await expect(page.getByText(/Restored 7 athletes/)).toBeVisible()
  await page.goto('/athletes')
  await page.getByLabel('Search athletes').fill('Backup Proof')
  await expect(page.getByRole('heading', { name: 'Backup Proof' })).toBeVisible()
})

test('standards versions connect to session setup and report export and print controls execute', async ({ page }) => {
  await page.goto('/standards')
  await page.getByRole('button', { name: /Create version/ }).click()
  await expect(page.getByLabel('New standard version')).toHaveValue('1.0.1')
  await page.getByRole('button', { name: /Save new version/ }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByLabel('Displayed standards version')).toHaveValue(/.+/)
  await page.goto('/testing/new')
  await expect(page.getByLabel('Scoring standard').getByRole('option', { name: /v1.0.1/ })).toHaveCount(1)

  await page.goto('/reporting/ath-a')
  const reportDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'CSV' }).click()
  expect((await reportDownload).suggestedFilename()).toBe('Jordan-Ellis-report.csv')
  await page.evaluate(() => { window.print = () => { document.body.dataset.printInvoked = 'true' } })
  await page.getByRole('button', { name: /Print/ }).click()
  await expect(page.locator('body')).toHaveAttribute('data-print-invoked', 'true')
})
