import { expect, test } from '@playwright/test'

test('real routes, deep links, history, and navigation work', async ({ page }) => {
  await page.goto('/athletes/ath-a')
  await expect(page.getByRole('heading', { name: 'Jordan Ellis', level: 1 })).toBeVisible()
  await page.reload()
  await expect(page).toHaveURL(/\/athletes\/ath-a$/)
  if ((page.viewportSize()?.width ?? 1000) <= 800) await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Testing' }).click()
  await expect(page).toHaveURL(/\/testing$/)
  await page.goBack()
  await expect(page).toHaveURL(/\/athletes\/ath-a$/)
})

test('live result autosaves to IndexedDB and survives reload', async ({ page }) => {
  await page.goto('/testing/session-draft/live')
  const input = page.getByLabel('Countermovement Vertical Jump attempt 1')
  await input.fill('24.5')
  await page.waitForTimeout(100)
  await page.reload()
  await expect(input).toHaveValue('24.5')
})

test('required pages have no viewport overflow', async ({ page }, testInfo) => {
  const routes = ['/', '/athletes', '/testing', '/testing/new', '/testing/session-draft/live', '/testing/session-complete/review', '/database', '/standards', '/reporting', '/reporting/ath-a']
  for (const route of routes) {
    await page.goto(route)
    await expect(page.locator('body')).toBeVisible()
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1)
    expect(overflow, `horizontal overflow at ${route}`).toBe(false)
  }
  await page.goto('/testing/session-draft/live')
  await page.screenshot({ path: `screenshots/live-${testInfo.project.name}.png`, fullPage: true })
  await page.goto('/')
  await page.screenshot({ path: `screenshots/dashboard-${testInfo.project.name}.png`, fullPage: true })
  await page.goto('/standards')
  await page.getByRole('button', { name: /Create version/ }).click()
  await expect(page.getByRole('heading', { name: 'Create scoring version' })).toBeVisible()
  const editorOverflow = await page.locator('.standards-modal').evaluate((element) => element.scrollWidth > element.clientWidth + 1)
  expect(editorOverflow, 'standards editor overflow').toBe(false)
  await page.screenshot({ path: `screenshots/standards-editor-${testInfo.project.name}.png` })
})

test('complete coach workflow creates, captures, publishes, locks, and reports one athlete', async ({ page }) => {
  await page.goto('/testing/new')
  await page.getByPlaceholder('Example: Fall baseline').fill('Acceptance Session')
  await expect(page.getByText('5 selected')).toBeVisible()
  await page.getByRole('button', { name: /Jordan Ellis/ }).click()
  await page.getByRole('button', { name: /Open live intake/ }).click()
  await expect(page).toHaveURL(/\/testing\/[^/]+\/live$/)
  await page.getByLabel('Countermovement Vertical Jump attempt 1').fill('24')
  await page.getByRole('tab', { name: /Broad jump/ }).click()
  await page.getByLabel('Standing Broad Jump attempt 1').fill('96')
  await page.getByRole('tab', { name: /10 yard/ }).click()
  await page.getByLabel('10 Yard Sprint attempt 1').fill('1.8')
  await page.getByRole('tab', { name: /Pro agility/ }).click()
  await page.getByLabel('5-10-5 Pro Agility attempt 1').fill('4.7')
  await page.getByRole('tab', { name: /Bench reps/ }).click()
  await page.getByLabel('Bench Press Repetitions attempt 1').fill('12')
  await page.getByRole('button', { name: /Review session/ }).click()
  await expect(page.getByText('5 / 5')).toBeVisible()
  const benchStatus = page.getByLabel('Jordan Ellis Bench Press Repetitions status')
  await benchStatus.selectOption('excluded')
  await expect(page.getByRole('button', { name: /Approve and publish/ })).toBeDisabled()
  await benchStatus.selectOption('valid')
  await page.getByRole('button', { name: /Approve and publish/ }).click()
  await expect(page.getByText('Published locally.')).toBeVisible()
  await page.getByRole('link', { name: /Open/ }).click()
  await expect(page.getByRole('heading', { name: 'Jordan Ellis', level: 1 })).toBeVisible()
  await expect(page.getByText(/v1.0.0/).first()).toBeVisible()
  await page.goto((await page.url()).replace(/\/reporting\/ath-a$/, '/testing'))
  await page.locator('article').filter({ hasText: 'Acceptance Session' }).getByRole('link', { name: /View published session/ }).click()
  await page.goto((await page.url()).replace(/\/review$/, '/live'))
  await expect(page.getByText(/published and locked/i)).toBeVisible()
})
