import { Search, UserPlus, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/ui'
import { db } from '../lib/db'
import { imageFileToDataUrl } from '../lib/images'
import { deriveAthleteReport, latestStandardsVersion, resolveReportVersion } from '../lib/report'
import { useData } from '../lib/useData'
import { initials } from '../lib/utils'

export default function AthletesPage() {
  const { athletes, sessions, measurements, standards } = useData(); const [query, setQuery] = useState(''); const [sport, setSport] = useState('All'); const [group, setGroup] = useState('All'); const [adding, setAdding] = useState(false); const [addError, setAddError] = useState('')
  const filtered = useMemo(() => athletes.filter((a) => `${a.firstName} ${a.lastName} ${a.positions.join(' ')} ${a.sports.join(' ')} ${a.grade}`.toLowerCase().includes(query.toLowerCase()) && (sport === 'All' || a.sports.includes(sport)) && (group === 'All' || a.group === group)), [athletes, query, sport, group])
  const sports = [...new Set(athletes.flatMap((a) => a.sports))].sort(); const groups = [...new Set(athletes.map((a) => a.group))].sort()
  const totalFor = (athleteId: string) => { const athlete = athletes.find((item) => item.id === athleteId); if (!athlete) return null; const version = resolveReportVersion(athleteId, sessions, standards) ?? latestStandardsVersion(standards); return version ? deriveAthleteReport(athlete, sessions, measurements, version, athletes) : null }
  async function addAthlete(formData: FormData) { const firstName = String(formData.get('firstName')).trim(); const lastName = String(formData.get('lastName')).trim(); if (athletes.some((athlete) => athlete.firstName.trim().toLowerCase() === firstName.toLowerCase() && athlete.lastName.trim().toLowerCase() === lastName.toLowerCase())) { setAddError('An athlete with this first and last name already exists.'); return } const sport = String(formData.get('sport')).trim(); const position = String(formData.get('position')).trim(); const additionalSports = String(formData.get('additionalSports')).split(',').map((value) => value.trim()).filter(Boolean); const additionalPositions = String(formData.get('additionalPositions')).split(',').map((value) => value.trim()).filter(Boolean); try { const photo = formData.get('photo'); const photoDataUrl = photo instanceof File && photo.size ? await imageFileToDataUrl(photo) : undefined; await db.athletes.add({ id: crypto.randomUUID(), firstName, lastName, sex: String(formData.get('sex')) as 'female' | 'male' | 'unspecified', dateOfBirth: String(formData.get('dateOfBirth')), grade: String(formData.get('grade')).trim(), sport, position, sports: [...new Set([sport, ...additionalSports].filter(Boolean))], positions: [...new Set([position, ...additionalPositions].filter(Boolean))], group: String(formData.get('group')).trim(), photoDataUrl, createdAt: new Date().toISOString() }); setAdding(false); setAddError('') } catch (error) { setAddError(error instanceof Error ? error.message : 'The athlete could not be saved to IndexedDB. Check browser storage access and try again.') } }
  return <div className="page"><PageHeader eyebrow="Roster" title="Athletes" description="Manage the people attached to assessments and individual reports." actions={<button className="button primary" onClick={() => setAdding(true)}><UserPlus size={18} />Add athlete</button>} />
    <section className="filter-bar"><label className="search-field"><Search size={18} /><input aria-label="Search athletes" placeholder="Search by name or position" value={query} onChange={(e) => setQuery(e.target.value)} /></label><label><span>Sport</span><select value={sport} onChange={(e) => setSport(e.target.value)}><option>All</option>{sports.map((value) => <option key={value}>{value}</option>)}</select></label><label><span>Group</span><select value={group} onChange={(e) => setGroup(e.target.value)}><option>All</option>{groups.map((value) => <option key={value}>{value}</option>)}</select></label><span className="result-count">{filtered.length} athletes</span></section>
    <section className="athlete-grid">{filtered.map((athlete) => { const report = totalFor(athlete.id); return <Link className="athlete-card" key={athlete.id} to={`/athletes/${athlete.id}`}><div className="avatar">{athlete.photoDataUrl ? <img src={athlete.photoDataUrl} alt="" /> : initials(athlete.firstName, athlete.lastName)}</div><div className="athlete-card-copy"><h3>{athlete.firstName} {athlete.lastName}</h3><p>{athlete.sports.join(' / ')} · {athlete.positions.join(' / ') || 'Position not set'}</p><span>{athlete.group} · Grade {athlete.grade || 'not set'}</span></div><div className="athlete-card-score"><strong>{report?.overall ?? '—'}</strong><span>{report?.overall === null || report?.overall === undefined ? 'Incomplete' : `of ${report.maxPoints} pts`}</span></div><div className="card-arrow">→</div></Link> })}</section>
    {adding && <div className="modal-backdrop" role="presentation"><div className="modal athlete-modal" role="dialog" aria-modal="true" aria-labelledby="add-title"><div className="modal-header"><div><p className="eyebrow">Roster record</p><h2 id="add-title">Add athlete</h2><p>Build the profile used for roster filters and standards matching.</p></div><button className="icon-button" aria-label="Close" onClick={() => { setAdding(false); setAddError('') }}><X /></button></div><form action={addAthlete}>{addError && <p className="validation-error" role="alert">{addError}</p>}<section className="form-section"><div className="form-section-title"><span>01</span><div><strong>Identity</strong><small>Required roster and demographic fields</small></div></div><div className="form-grid"><label>First name<input name="firstName" required /></label><label>Last name<input name="lastName" required /></label><label>Sex<select name="sex" defaultValue="unspecified"><option value="unspecified">Not specified</option><option value="female">Female</option><option value="male">Male</option></select></label><label>Date of birth<input name="dateOfBirth" type="date" /></label><label>Grade<input name="grade" placeholder="Example: 10" /></label><label>Training group<input name="group" required placeholder="Example: Varsity" /></label><label className="wide">Athlete photo<input name="photo" type="file" accept="image/*" /></label></div></section><section className="form-section"><div className="form-section-title"><span>02</span><div><strong>Sport profile</strong><small>Primary and secondary roles</small></div></div><div className="form-grid"><label>Primary sport<input name="sport" required /></label><label>Primary position<input name="position" /></label><label>Additional sports<input name="additionalSports" placeholder="Track, Basketball" /></label><label>Additional positions<input name="additionalPositions" placeholder="Sprinter, Forward" /></label></div><p className="field-help">Separate additional sports and positions with commas. Every value becomes available to standards matching.</p></section><div className="modal-actions"><button type="button" className="button secondary" onClick={() => { setAdding(false); setAddError('') }}>Cancel</button><button className="button primary">Add athlete</button></div></form></div></div>}
  </div>
}
