import { Activity, ArrowLeft, FileText, TrendingUp } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState, PageHeader, ScoreBadge, StatusPill } from '../components/ui'
import { deriveAthleteReport, latestStandardsVersion, resolveReportVersion } from '../lib/report'
import { athleteAgeOn } from '../lib/standards'
import { useData } from '../lib/useData'
import { displayDate, initials } from '../lib/utils'

export default function AthletePage() {
  const { athleteId } = useParams(); const { athletes, sessions, measurements, standards } = useData(); const athlete = athletes.find((a) => a.id === athleteId); const version = athlete ? resolveReportVersion(athlete.id, sessions, standards) ?? latestStandardsVersion(standards) : undefined
  if (!athlete || !version) return <div className="page"><EmptyState title="Athlete not found">This athlete is not in the local database.</EmptyState></div>
  const report = deriveAthleteReport(athlete, sessions, measurements, version)
  const age = athleteAgeOn(athlete.dateOfBirth, new Date().toISOString().slice(0, 10))
  return <div className="page"><Link className="back-link" to="/athletes"><ArrowLeft size={16} />Athletes</Link><PageHeader title={`${athlete.firstName} ${athlete.lastName}`} description={`${athlete.sport} · ${athlete.position || 'Position not set'} · Grade ${athlete.grade || 'not set'} · ${athlete.group}`} actions={<Link className="button primary" to={`/reporting/${athlete.id}`}><FileText size={18} />View report</Link>} />
    <section className="profile-summary panel"><div className="avatar xl">{initials(athlete.firstName, athlete.lastName)}</div><div className="identity"><p className="eyebrow">Athlete profile</p><h2>{athlete.firstName} {athlete.lastName}</h2><div className="identity-facts"><span>{athlete.sex === 'unspecified' ? 'Sex not specified' : athlete.sex}</span><span>{age === null ? 'Age not available' : `Age ${age}`}</span><span>{athlete.dateOfBirth ? `Born ${displayDate(athlete.dateOfBirth)}` : 'Birth date not set'}</span><span>Grade {athlete.grade || 'not set'}</span></div><div className="profile-tags">{athlete.sports.map((sport) => <span key={sport}>{sport}</span>)}{athlete.positions.map((position) => <span key={position}>{position}</span>)}</div></div><ScoreBadge score={report.overall} maxPoints={report.maxPoints} label={`Point total · v${version.version}`} /></section>
    <section className="profile-contract"><div><span>Applied standards profile</span><strong>{report.profile.name}</strong><small>Resolved from sex, age, grade, sport, and position rules.</small></div><div><span>Primary sport</span><strong>{athlete.sport}</strong><small>{athlete.sports.length} sport{athlete.sports.length === 1 ? '' : 's'} on profile</small></div><div><span>Training group</span><strong>{athlete.group}</strong><small>Local roster classification</small></div></section>
    <div className="profile-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Latest assessment</p><h2>Metric grades</h2></div>{report.latestSession && <span>{displayDate(report.latestSession.date)}</span>}</div>{report.scores.length ? <div className="metric-list">{report.scores.map((score) => <div className="metric-row" key={score.metric.id}><div><strong>{score.metric.name}</strong><span>{score.value} {score.metric.unit}</span></div><div className="mini-bar"><span style={{ width: `${score.points / 4 * 100}%`, background: score.band.color }} /></div><StatusPill tone={score.points >= 3 ? 'good' : score.points >= 2 ? 'ready' : 'warning'}>{score.points}/4 · {score.band.label}</StatusPill></div>)}</div> : <EmptyState title="No published results">Publish a complete assessment to create metric grades.</EmptyState>}</section>
      <section className="panel"><div className="section-heading"><div><p className="eyebrow">History</p><h2>Assessment sessions</h2></div></div>{report.sessions.length ? <div className="timeline">{report.sessions.map((session) => { const sessionVersion = standards.find((item) => item.id === session.standardsVersionId); return <div key={session.id}><span className="timeline-dot"><Activity size={14} /></span><div><strong>{session.name}</strong><p>{displayDate(session.date)} · {sessionVersion ? `Standard v${sessionVersion.version}` : 'Standard unavailable'}</p></div><Link to={`/testing/${session.id}/review`}>Review</Link></div> })}</div> : <EmptyState title="No history yet">This athlete has no published assessment sessions.</EmptyState>}</section>
    </div><section className="panel"><div className="section-heading"><div><p className="eyebrow">Longitudinal view</p><h2>Metric history</h2></div><TrendingUp size={20} /></div><div className="history-grid">{version.metrics.map((metric) => { const points = report.sessions.flatMap((s) => measurements.filter((m) => m.sessionId === s.id && m.athleteId === athlete.id && m.metricId === metric.id && m.selectedAttempt !== null)); return <div className="history-card" key={metric.id}><span>{metric.shortName}</span><strong>{points[0]?.selectedAttempt ?? 'No result'} <small>{points.length ? metric.unit : ''}</small></strong><p>{points.length} published result{points.length === 1 ? '' : 's'}</p></div> })}</div></section>
  </div>
}
