import { ArrowRight, CheckCircle2, ClipboardCheck, Clock3, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader, Progress, StatusPill } from '../components/ui'
import { deriveAthleteReport, latestStandardsVersion, resolveReportVersion } from '../lib/report'
import { useData } from '../lib/useData'
import { displayDate } from '../lib/utils'

export default function DashboardPage() {
  const { athletes, sessions, measurements, standards } = useData()
  const recent = [...sessions].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4)
  const incomplete = sessions.filter((session) => session.status !== 'published')
  const published = sessions.filter((session) => session.status === 'published').length
  const reports = athletes.flatMap((athlete) => { const version = resolveReportVersion(athlete.id, sessions, standards) ?? latestStandardsVersion(standards); return version ? [deriveAthleteReport(athlete, sessions, measurements, version)] : [] })
  const completed = reports.filter((report) => report.overall !== null).sort((a, b) => (b.overall ?? 0) - (a.overall ?? 0))
  const metricGrades = (latestStandardsVersion(standards)?.metrics ?? []).map((metric) => { const scores = completed.flatMap((report) => report.scores.filter((score) => score.metric.id === metric.id)); return { id: metric.id, label: metric.shortName, average: scores.length ? scores.reduce((sum, score) => sum + score.points, 0) / scores.length : 0 } })
  const female = athletes.filter((athlete) => athlete.sex === 'female').length; const male = athletes.filter((athlete) => athlete.sex === 'male').length; const unspecified = athletes.length - female - male
  const meanPoints = completed.length ? completed.reduce((sum, report) => sum + (report.overall ?? 0), 0) / completed.length : 0

  return <div className="page dashboard-page"><PageHeader eyebrow="Performance operations" title="Assessment command center" description="Roster readiness, point totals, metric grades, and unfinished assessment work from this local database." actions={<Link className="button primary" to="/testing/new">New assessment</Link>} />
    <section className="stat-grid"><div className="stat-card"><Users /><span>Active roster</span><strong>{athletes.length}</strong><small>{female} female · {male} male{unspecified ? ` · ${unspecified} unspecified` : ''}</small></div><div className="stat-card"><ClipboardCheck /><span>Published sessions</span><strong>{published}</strong><small>{completed.length} athletes with totals</small></div><div className="stat-card"><Clock3 /><span>Needs attention</span><strong>{incomplete.length}</strong><small>Draft, live, or in review</small></div><div className="stat-card"><CheckCircle2 /><span>Mean point total</span><strong>{completed.length ? meanPoints.toFixed(1) : '—'}</strong><small>Out of {completed[0]?.maxPoints ?? 20} available points</small></div></section>

    <section className="analytics-grid">
      <article className="panel points-chart"><div className="section-heading"><div><p className="eyebrow">Published scoring</p><h2>Athlete point totals</h2></div><span>Sum of 0–4 metric grades</span></div>{completed.length ? <div className="leader-bars" role="img" aria-label="Published athlete point totals">{completed.map((report, index) => <Link to={`/athletes/${report.athlete.id}`} className="leader-row" key={report.athlete.id}><span className="leader-rank">{String(index + 1).padStart(2, '0')}</span><strong>{report.athlete.firstName} {report.athlete.lastName}</strong><div className="leader-track"><span style={{ width: `${(report.overall ?? 0) / report.maxPoints * 100}%` }} /></div><b>{report.overall}<small>/{report.maxPoints}</small></b></Link>)}</div> : <p className="muted">Publish a complete assessment to populate point totals.</p>}</article>
      <article className="panel grade-chart"><div className="section-heading"><div><p className="eyebrow">Cohort profile</p><h2>Average grade by metric</h2></div><span>0 to 4</span></div><div className="vertical-chart" role="img" aria-label="Average grade by metric">{metricGrades.map((metric) => <div className="grade-column" key={metric.id}><div className="grade-value">{metric.average.toFixed(1)}</div><div className="grade-track"><span style={{ height: `${metric.average / 4 * 100}%` }} /></div><strong>{metric.label}</strong></div>)}</div></article>
      <article className="panel coverage-chart"><div><p className="eyebrow">Standards inputs</p><h2>Roster profile coverage</h2><p>Sex is one of five available standards dimensions. Age, grade, sport, and position are resolved per athlete when a session opens.</p></div><div className="coverage-visual" role="img" aria-label={`${female} female, ${male} male, ${unspecified} unspecified athletes`} style={{ background: `conic-gradient(#0b95a3 0 ${athletes.length ? female / athletes.length * 100 : 0}%, #273c58 0 ${athletes.length ? (female + male) / athletes.length * 100 : 0}%, #c7d1d5 0)` }}><div><strong>{athletes.length}</strong><span>athletes</span></div></div><div className="coverage-legend"><span><i className="female" />Female <strong>{female}</strong></span><span><i className="male" />Male <strong>{male}</strong></span><span><i className="unspecified" />Unspecified <strong>{unspecified}</strong></span></div></article>
    </section>

    <div className="dashboard-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Continue working</p><h2>Incomplete assessments</h2></div><Link to="/testing">View all</Link></div>{incomplete.length ? <div className="work-list">{incomplete.map((session) => { const captured = measurements.filter((measurement) => measurement.sessionId === session.id && measurement.selectedAttempt !== null).length; const total = session.athleteIds.length * session.metricIds.length; return <div className="work-item" key={session.id}><div className="work-icon"><Clock3 size={20} /></div><div className="work-copy"><strong>{session.name}</strong><span>{displayDate(session.date)} · {session.athleteIds.length} athletes</span><Progress value={captured} max={total} /></div><div className="work-status"><span>{captured} of {total}</span><Link className="icon-link" aria-label={`Continue ${session.name}`} to={session.status === 'review' ? `/testing/${session.id}/review` : `/testing/${session.id}/live`}><ArrowRight /></Link></div></div>})}</div> : <p className="muted">All sessions are published.</p>}</section>
      <aside className="panel quick-start"><p className="eyebrow">Next actions</p><h2>Keep the work moving</h2><Link to="/athletes"><span>1</span><div><strong>Complete athlete profiles</strong><small>Add demographics, sports, positions, and grade.</small></div><ArrowRight /></Link><Link to="/standards"><span>2</span><div><strong>Define audience standards</strong><small>Target sex, age, grade, sport, or position.</small></div><ArrowRight /></Link><Link to="/testing/new"><span>3</span><div><strong>Start a testing session</strong><small>Pin one profile per athlete and capture results.</small></div><ArrowRight /></Link></aside>
    </div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Assessment log</p><h2>Recent sessions</h2></div></div><div className="table-scroll"><table><thead><tr><th>Session</th><th>Date</th><th>Roster</th><th>Standard</th><th>Status</th><th /></tr></thead><tbody>{recent.map((session) => { const version = standards.find((item) => item.id === session.standardsVersionId); return <tr key={session.id}><td><strong>{session.name}</strong></td><td>{displayDate(session.date)}</td><td>{session.athleteIds.length} athletes</td><td>{version ? `${version.name} · v${version.version}` : 'Version unavailable'}</td><td><StatusPill tone={session.status === 'published' ? 'good' : session.status === 'review' ? 'ready' : 'warning'}>{session.status.replace('_', ' ')}</StatusPill></td><td><Link to={session.status === 'published' || session.status === 'review' ? `/testing/${session.id}/review` : `/testing/${session.id}/live`}>Open</Link></td></tr> })}</tbody></table></div></section>
  </div>
}
