import { Database, Download, FileDown, FileUp, HardDrive, RotateCcw, ShieldCheck } from 'lucide-react'
import { useRef, useState } from 'react'
import { Notice, PageHeader, StatusPill } from '../components/ui'
import { athletesToCsv, CSV_TEMPLATE, downloadText, parseAthleteCsv, type CsvRowResult } from '../lib/csv'
import { db, resetDemo } from '../lib/db'
import { useData } from '../lib/useData'
import type { ImportRecord } from '../lib/types'
import { displayDate } from '../lib/utils'

export default function DatabasePage() {
  const { athletes, sessions, measurements, imports } = useData(); const input = useRef<HTMLInputElement>(null); const [fileName, setFileName] = useState(''); const [rows, setRows] = useState<CsvRowResult[]>([]); const [fatalErrors, setFatalErrors] = useState<string[]>([]); const [imported, setImported] = useState(false)
  async function readFile(file?: File) { if (!file) return; setFileName(file.name); setImported(false); const parsed = parseAthleteCsv(await file.text(), athletes); setRows(parsed.rows); setFatalErrors(parsed.fatalErrors) }
  async function importValid() { const valid = rows.flatMap((row) => row.athlete ? [row.athlete] : []); if (!valid.length || fatalErrors.length) return; await db.transaction('rw', db.athletes, db.imports, async () => { await db.athletes.bulkAdd(valid); const record: ImportRecord = { id: crypto.randomUUID(), importedAt: new Date().toISOString(), fileName, totalRows: rows.length, added: valid.length, skipped: rows.length - valid.length, errors: rows.filter((r) => r.errors.length).length }; await db.imports.add(record) }); setImported(true) }
  async function exportAll() { const payload = { exportedAt: new Date().toISOString(), formatVersion: 1, athletes: await db.athletes.toArray(), sessions: await db.sessions.toArray(), measurements: await db.measurements.toArray(), standards: await db.standards.toArray() }; downloadText(`fieldhouse-backup-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify(payload, null, 2), 'application/json') }
  async function reset() { if (window.confirm('Replace all local data with the clearly labeled synthetic demo? Export a backup first if needed.')) { await resetDemo(); setRows([]); setImported(false) } }
  return <div className="page"><PageHeader eyebrow="Data operations" title="Local database" description="Import, validate, export, and reset the browser database on this device." actions={<button className="button secondary" onClick={exportAll}><Download size={17} />Export full backup</button>} />
    <Notice><strong>Local data boundary.</strong> Athlete data is stored in IndexedDB inside this browser profile. Nothing in this starter sends athlete records to Arkitect, Arketype, or any remote service. Clearing browser site data can remove it, so export regular backups.</Notice>
    <section className="database-cards"><div className="panel data-stat"><HardDrive /><div><span>Storage engine</span><strong>IndexedDB</strong><small>Persistent browser database</small></div><StatusPill tone="good">Ready</StatusPill></div><div className="panel data-stat"><ShieldCheck /><div><span>Data location</span><strong>This device</strong><small>No configured remote data plane</small></div><StatusPill tone="good">Local</StatusPill></div><div className="panel data-stat"><Database /><div><span>Current records</span><strong>{athletes.length} athletes</strong><small>{sessions.length} sessions · {measurements.length} results</small></div><StatusPill>Synthetic demo</StatusPill></div></section>
    <div className="database-layout"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Roster import</p><h2>Import athletes from CSV</h2></div><button className="button secondary" onClick={() => downloadText('fieldhouse-athlete-template.csv', CSV_TEMPLATE)}><FileDown size={17} />Download template</button></div><ol className="import-steps"><li><span>1</span>Download the template and add athlete rows.</li><li><span>2</span>Upload the CSV to preview mapping and validation.</li><li><span>3</span>Import valid rows. Rows with errors remain visible.</li></ol><input ref={input} hidden type="file" accept=".csv,text/csv" onChange={(e) => readFile(e.target.files?.[0])} /><button className="upload-zone" onClick={() => input.current?.click()}><FileUp size={28} /><strong>Choose a CSV file</strong><span>Expected fields: first name, last name, sport, position, and group</span></button>
      {fileName && <div className="import-preview"><div className="section-heading"><div><p className="eyebrow">Validation preview</p><h3>{fileName}</h3></div><span>{rows.filter((r) => r.athlete).length} valid · {rows.filter((r) => r.errors.length).length} with errors</span></div>{fatalErrors.map((error) => <Notice key={error} tone="warning">{error}</Notice>)}<div className="mapping-row">{['CSV field', 'Maps to', 'Status'].map((value) => <strong key={value}>{value}</strong>)}{[['first_name', 'First name'], ['last_name', 'Last name'], ['sport', 'Sport'], ['position', 'Position'], ['group', 'Group']].flatMap(([from, to]) => [<span key={`${from}-a`}>{from}</span>, <span key={`${from}-b`}>{to}</span>, <StatusPill key={`${from}-c`} tone="good">Mapped</StatusPill>])}</div><div className="table-scroll"><table><thead><tr><th>Row</th><th>Name</th><th>Sport</th><th>Group</th><th>Validation</th></tr></thead><tbody>{rows.map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.raw.first_name} {row.raw.last_name}</td><td>{row.raw.sport}</td><td>{row.raw.group}</td><td>{row.errors.length ? <span className="validation-error">{row.errors.join(' ')}</span> : <StatusPill tone="good">Valid</StatusPill>}</td></tr>)}</tbody></table></div><button className="button primary" disabled={fatalErrors.length > 0 || !rows.some((r) => r.athlete) || imported} onClick={importValid}>{imported ? 'Valid rows imported' : `Import ${rows.filter((r) => r.athlete).length} valid rows`}</button></div>}
    </section><aside className="database-side"><section className="panel"><p className="eyebrow">Portable exports</p><h2>Roster CSV</h2><p>Download the current roster for a spreadsheet or another coaching system.</p><button className="button secondary full" onClick={() => downloadText('fieldhouse-athletes.csv', athletesToCsv(athletes))}><FileDown size={17} />Export roster CSV</button></section><section className="panel danger-zone"><p className="eyebrow">Demo controls</p><h2>Reset synthetic demo</h2><p>This removes all local changes and restores the clearly labeled synthetic roster, sessions, and results.</p><button className="button danger full" onClick={reset}><RotateCcw size={17} />Reset demo data</button></section></aside></div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Audit trail</p><h2>Import history</h2></div></div>{imports.length ? <div className="table-scroll"><table><thead><tr><th>File</th><th>Date</th><th>Rows</th><th>Added</th><th>Skipped</th><th>Errors</th></tr></thead><tbody>{imports.map((record) => <tr key={record.id}><td><strong>{record.fileName}</strong></td><td>{displayDate(record.importedAt.slice(0, 10))}</td><td>{record.totalRows}</td><td>{record.added}</td><td>{record.skipped}</td><td>{record.errors}</td></tr>)}</tbody></table></div> : <p className="muted">No CSV files have been imported on this device.</p>}</section>
  </div>
}
