import { AlertTriangle, ArrowLeft, Check, CheckCircle2, ChevronRight, Cloud, RotateCcw } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Notice, Progress, StatusPill } from '../components/ui'
import { db } from '../lib/db'
import { bestAttempt, isMetricValueValid, scoreMetric } from '../lib/scoring'
import { bandsForMetric, resolveStandardsProfile } from '../lib/standards'
import type { Measurement } from '../lib/types'
import { useData } from '../lib/useData'
import { initials } from '../lib/utils'

export default function LiveTestingPage() {
  const { sessionId } = useParams(); const navigate = useNavigate(); const { athletes, sessions, measurements, standards } = useData(); const session = sessions.find((s) => s.id === sessionId); const version = standards.find((s) => s.id === session?.standardsVersionId)
  const roster = useMemo(() => athletes.filter((a) => session?.athleteIds.includes(a.id)), [athletes, session]); const metrics = useMemo(() => version?.metrics.filter((m) => session?.metricIds.includes(m.id)) ?? [], [version, session])
  const [athleteId, setAthleteId] = useState(''); const [metricId, setMetricId] = useState(''); const [saveState, setSaveState] = useState('Saved'); const [saveError, setSaveError] = useState(''); const pendingSave = useRef<Promise<void>>(Promise.resolve()); const saveFailed = useRef(false)
  useEffect(() => { if (!athleteId && roster[0]) setAthleteId(roster[0].id); if (!metricId && metrics[0]) setMetricId(metrics[0].id) }, [athleteId, metricId, roster, metrics])
  const athlete = roster.find((a) => a.id === athleteId); const metric = metrics.find((m) => m.id === metricId); const current = measurements.find((m) => m.sessionId === sessionId && m.athleteId === athleteId && m.metricId === metricId); const profile = athlete && version ? version.profiles.find((item) => item.id === session?.profileIdsByAthlete?.[athlete.id]) ?? resolveStandardsProfile(version, athlete, session?.date ?? new Date().toISOString().slice(0, 10)) : undefined
  const captured = measurements.filter((m) => m.sessionId === sessionId && m.selectedAttempt !== null && m.status === 'valid').length; const total = roster.length * metrics.length
  const athleteCompletion = (id: string) => measurements.filter((m) => m.sessionId === sessionId && m.athleteId === id && m.selectedAttempt !== null && m.status === 'valid').length
  const liveScores = useMemo(() => metrics.flatMap((m) => { const result = measurements.find((x) => x.sessionId === sessionId && x.athleteId === athleteId && x.metricId === m.id && x.selectedAttempt !== null && x.status === 'valid'); return result?.selectedAttempt === null || result?.selectedAttempt === undefined ? [] : [scoreMetric(m, result.selectedAttempt, profile ? bandsForMetric(profile, m.id, m.bands) : m.bands)] }), [metrics, measurements, sessionId, athleteId, profile])
  if (!session || !version) return <div className="page"><Notice tone="warning">This session is not available in the local database.</Notice></div>
  if (session.status === 'published') return <div className="page"><Notice tone="warning"><strong>This session is published and locked.</strong> Published measurements cannot be changed from live intake.</Notice><Link className="button primary" to={`/testing/${session.id}/review`}>Open published review</Link></div>
  function saveAttempt(index: number, raw: string) { if (!metric || !athlete) return; const targetMetric = metric; const targetAthlete = athlete; const parsed = raw === '' ? null : Number(raw); setSaveState('Saving'); setSaveError(''); saveFailed.current = false; pendingSave.current = pendingSave.current.catch(() => undefined).then(async () => { const stored = await db.measurements.where('[sessionId+athleteId+metricId]').equals([session!.id, targetAthlete.id, targetMetric.id]).first(); const attempts = stored?.attempts ? [...stored.attempts] : Array(targetMetric.attempts).fill(null); attempts[index] = parsed; const selectedAttempt = bestAttempt(targetMetric, attempts); const nextStatus = selectedAttempt !== null && !isMetricValueValid(targetMetric, selectedAttempt) ? 'invalid' : stored?.status === 'excluded' ? 'excluded' : 'valid'; const measurement: Measurement = { id: stored?.id ?? crypto.randomUUID(), sessionId: session!.id, athleteId: targetAthlete.id, metricId: targetMetric.id, attempts, selectedAttempt, status: nextStatus, updatedAt: new Date().toISOString() }; await db.measurements.put(measurement); await db.sessions.update(session!.id, { updatedAt: new Date().toISOString() }) }).then(() => setSaveState('Saved')).catch(() => { saveFailed.current = true; setSaveState('Save failed'); setSaveError('This result could not be saved to IndexedDB. Check browser storage access, then edit the value to retry.') }) }
  async function clearResult() { if (!current) return; setSaveState('Saving'); setSaveError(''); try { await pendingSave.current; await db.measurements.delete(current.id); setSaveState('Saved') } catch { saveFailed.current = true; setSaveState('Save failed'); setSaveError('This result could not be cleared from IndexedDB. Try again before leaving live intake.') } }
  async function openReview() { await pendingSave.current; if (saveFailed.current) return; await db.sessions.update(session!.id, { status: 'review', updatedAt: new Date().toISOString() }); navigate(`/testing/${session!.id}/review`) }
  function nextAthlete() { const index = roster.findIndex((a) => a.id === athleteId); setAthleteId(roster[(index + 1) % roster.length]?.id ?? '') }
  const invalid = current?.selectedAttempt !== null && current?.selectedAttempt !== undefined && metric ? !isMetricValueValid(metric, current.selectedAttempt) : false
  return <div className="live-page"><header className="live-header"><div><Link className="back-link" to="/testing"><ArrowLeft size={16} />Testing</Link><h1>{session.name}</h1><p>{roster.length} athletes · {metrics.length} tests · Standard v{version.version}</p></div><div className="live-progress"><div><span>{captured} of {total} results</span><strong>{Math.round(captured / Math.max(total, 1) * 100)}%</strong></div><Progress value={captured} max={total} /></div><div className="autosave"><Cloud size={17} /><span>{saveState}</span><small>IndexedDB</small></div><button className="button primary" disabled={saveState === 'Saving' || saveState === 'Save failed'} onClick={openReview}>Review session<ChevronRight size={17} /></button></header>
    <div className="live-layout"><aside className="queue-panel"><div className="queue-heading"><div><p className="eyebrow">Athlete queue</p><h2>Roster</h2></div><span>{roster.filter((a) => athleteCompletion(a.id) === metrics.length).length} complete</span></div><div className="queue-list">{roster.map((person, index) => { const count = athleteCompletion(person.id); return <button key={person.id} onClick={() => setAthleteId(person.id)} className={person.id === athleteId ? 'active' : ''}><span className="queue-order">{String(index + 1).padStart(2, '0')}</span><span className="avatar small">{initials(person.firstName, person.lastName)}</span><span className="queue-name"><strong>{person.firstName} {person.lastName}</strong><small>{person.position} · {person.group}</small></span><span className={`completion-dot ${count === metrics.length ? 'complete' : ''}`}>{count === metrics.length ? <Check size={13} /> : `${count}/${metrics.length}`}</span></button> })}</div></aside>
      <main className="capture-panel"><div className="capture-athlete"><div className="avatar">{athlete && initials(athlete.firstName, athlete.lastName)}</div><div><p className="eyebrow">Now testing</p><h2>{athlete?.firstName} {athlete?.lastName}</h2><span>{athlete?.sport} · {athlete?.position}</span></div><button className="button secondary" onClick={nextAthlete}>Next athlete<ChevronRight size={17} /></button></div>
        <div className="metric-tabs" role="tablist" aria-label="Assessment metrics">{metrics.map((item) => { const result = measurements.find((m) => m.sessionId === session.id && m.athleteId === athleteId && m.metricId === item.id); return <button role="tab" aria-selected={item.id === metricId} key={item.id} className={item.id === metricId ? 'active' : ''} onClick={() => setMetricId(item.id)}>{result?.selectedAttempt !== null && result?.selectedAttempt !== undefined ? <CheckCircle2 size={15} /> : <span className="empty-circle" />}{item.shortName}</button> })}</div>
        {metric && <section className="capture-card"><div className="capture-card-head"><div><p className="eyebrow">{metric.direction === 'higher' ? 'Higher is better' : 'Lower is better'}</p><h2>{metric.name}</h2><p>Record {metric.attempts} attempt{metric.attempts === 1 ? '' : 's'}. The best valid attempt is selected automatically.</p></div><span className="unit-badge">{metric.unit}</span></div>
          {saveError && <Notice tone="warning"><strong>Save failed.</strong> {saveError}</Notice>}
          <div className="attempt-grid">{Array.from({ length: metric.attempts }, (_, index) => <label key={index}><span>Attempt {index + 1}</span><div className="attempt-input"><input aria-label={`${metric.name} attempt ${index + 1}`} type="number" min={metric.validMin} max={metric.validMax} step={metric.unit === 's' ? '0.01' : metric.unit === 'in' ? '0.1' : '1'} value={current?.attempts[index] ?? ''} onChange={(e) => saveAttempt(index, e.target.value)} /><small>{metric.unit}</small></div></label>)}</div>
          {invalid ? <Notice tone="warning"><strong>Check this value.</strong> {metric.name} must be between {metric.validMin} and {metric.validMax} {metric.unit}. This result is saved as invalid until corrected or excluded in review.</Notice> : current?.selectedAttempt !== null && current?.selectedAttempt !== undefined ? (() => { const grade = scoreMetric(metric, current.selectedAttempt, profile ? bandsForMetric(profile, metric.id, metric.bands) : metric.bands); return <div className="live-feedback"><div><span>Selected result</span><strong>{current.selectedAttempt} {metric.unit}</strong></div><div><span>Live grade</span><strong>{grade.points} / 4</strong></div><StatusPill tone={grade.points >= 3 ? 'good' : grade.points >= 2 ? 'ready' : 'warning'}>{grade.band.label}</StatusPill><small>{profile?.name ?? 'General profile'}</small></div> })() : <Notice>Enter the first attempt to see immediate grading feedback. Valid range: {metric.validMin} to {metric.validMax} {metric.unit}.</Notice>}
          <div className="capture-actions"><button className="button secondary" onClick={clearResult}><RotateCcw size={16} />Clear result</button><button className="button primary" onClick={() => { const idx = metrics.findIndex((m) => m.id === metricId); setMetricId(metrics[(idx + 1) % metrics.length]?.id ?? '') }}>Next metric<ChevronRight size={17} /></button></div>
        </section>}
      </main>
      <aside className="results-rail"><div className="queue-heading"><div><p className="eyebrow">Live grades</p><h2>{athlete?.firstName}</h2></div><strong>{liveScores.reduce((sum, score) => sum + score.points, 0)} pts</strong></div>{liveScores.length ? <div className="live-score-list">{liveScores.map((score) => <button key={score.metric.id} onClick={() => setMetricId(score.metric.id)}><div><strong>{score.metric.shortName}</strong><span>{score.value} {score.metric.unit}</span></div><strong style={{ color: score.band.color }}>{score.points}/4</strong></button>)}</div> : <div className="rail-empty"><AlertTriangle size={20} /><p>Grades appear here as valid results are saved.</p></div>}<div className="rail-note"><strong>{profile?.name ?? 'General profile'} · v{version.version}</strong><span>Editable starter bands. Not validated population norms.</span></div></aside>
    </div>
  </div>
}
