import { ArrowLeft, Check, ChevronRight } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { PageHeader } from '../components/ui'
import { db } from '../lib/db'
import { latestStandardsVersion } from '../lib/report'
import { resolveStandardsProfile } from '../lib/standards'
import { useData } from '../lib/useData'
import { initials, localISODate } from '../lib/utils'

export default function NewSessionPage() {
  const { athletes, standards } = useData(); const navigate = useNavigate(); const latest = latestStandardsVersion(standards); const [selectedVersionId, setSelectedVersionId] = useState(''); const version = standards.find((item) => item.id === selectedVersionId) ?? latest; const [name, setName] = useState(''); const [date, setDate] = useState(localISODate()); const [selectedAthletes, setSelectedAthletes] = useState<string[]>([]); const [selectedMetrics, setSelectedMetrics] = useState<string[]>([])
  useEffect(() => { if (!selectedVersionId && latest) { setSelectedVersionId(latest.id); setSelectedMetrics(latest.metrics.map((metric) => metric.id)) } }, [latest, selectedVersionId])
  const toggle = (list: string[], value: string, set: (next: string[]) => void) => set(list.includes(value) ? list.filter((id) => id !== value) : [...list, value])
  async function create() { if (!version || !name.trim() || !selectedAthletes.length || !selectedMetrics.length) return; const id = crypto.randomUUID(); const now = new Date().toISOString(); const profileIdsByAthlete = Object.fromEntries(athletes.filter((athlete) => selectedAthletes.includes(athlete.id)).map((athlete) => [athlete.id, resolveStandardsProfile(version, athlete, date).id])); await db.sessions.add({ id, name: name.trim(), date, athleteIds: selectedAthletes, metricIds: selectedMetrics, standardsVersionId: version.id, profileIdsByAthlete, status: 'in_progress', createdAt: now, updatedAt: now }); navigate(`/testing/${id}/live`) }
  function selectVersion(id: string) { const next = standards.find((item) => item.id === id); if (!next) return; setSelectedVersionId(id); setSelectedMetrics(next.metrics.map((metric) => metric.id)) }
  return <div className="page"><Link className="back-link" to="/testing"><ArrowLeft size={16} />Testing</Link><PageHeader eyebrow="Session setup" title="New assessment" description="Choose the battery and athletes before opening live intake." />
    <div className="setup-layout"><section className="panel setup-main"><div className="setup-section"><div className="step-number">1</div><div className="setup-body"><h2>Session details</h2><div className="form-grid"><label className="wide">Session name<input placeholder="Example: Fall baseline" value={name} onChange={(e) => setName(e.target.value)} /></label><label>Date<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><label>Scoring standard<select aria-label="Scoring standard" value={version?.id ?? ''} onChange={(event) => selectVersion(event.target.value)}>{[...standards].sort((a, b) => b.effectiveDate.localeCompare(a.effectiveDate)).map((item) => <option key={item.id} value={item.id}>{item.name} · v{item.version}</option>)}</select></label></div></div></div>
      <div className="setup-section"><div className="step-number">2</div><div className="setup-body"><div className="section-heading"><div><h2>Select tests</h2><p>Required metrics stay selected so every session can reach publication. Optional metrics can be added or removed.</p></div><span>{selectedMetrics.length} selected</span></div><div className="choice-list">{version?.metrics.map((metric) => <button key={metric.id} disabled={metric.required} className={selectedMetrics.includes(metric.id) ? 'selected' : ''} onClick={() => toggle(selectedMetrics, metric.id, setSelectedMetrics)}><span className="checkbox">{selectedMetrics.includes(metric.id) && <Check size={14} />}</span><div><strong>{metric.name}</strong><small>{metric.required ? 'Required · ' : ''}{metric.unit} · {metric.direction === 'higher' ? 'Higher is better' : 'Lower is better'} · {metric.attempts} attempt{metric.attempts === 1 ? '' : 's'}</small></div></button>)}</div></div></div>
      <div className="setup-section"><div className="step-number">3</div><div className="setup-body"><div className="section-heading"><div><h2>Select roster</h2><p>Choose athletes. Their matching standards profiles are pinned when live intake opens.</p></div><button className="text-button" onClick={() => setSelectedAthletes(selectedAthletes.length === athletes.length ? [] : athletes.map((a) => a.id))}>{selectedAthletes.length === athletes.length ? 'Clear all' : 'Select all'}</button></div><div className="roster-picker">{athletes.map((athlete) => <button key={athlete.id} className={selectedAthletes.includes(athlete.id) ? 'selected' : ''} onClick={() => toggle(selectedAthletes, athlete.id, setSelectedAthletes)}><span className="checkbox">{selectedAthletes.includes(athlete.id) && <Check size={14} />}</span><span className="avatar small">{initials(athlete.firstName, athlete.lastName)}</span><div><strong>{athlete.firstName} {athlete.lastName}</strong><small>{athlete.position} · Grade {athlete.grade || 'not set'} · {version ? resolveStandardsProfile(version, athlete, date).name : 'No profile'}</small></div></button>)}</div></div></div></section>
      <aside className="panel setup-summary"><p className="eyebrow">Session summary</p><h2>{name || 'Untitled assessment'}</h2><dl><div><dt>Date</dt><dd>{date}</dd></div><div><dt>Athletes</dt><dd>{selectedAthletes.length}</dd></div><div><dt>Metrics</dt><dd>{selectedMetrics.length}</dd></div><div><dt>Expected results</dt><dd>{selectedAthletes.length * selectedMetrics.length}</dd></div></dl><button className="button primary full" disabled={!name.trim() || !selectedAthletes.length || !selectedMetrics.length} onClick={create}>Open live intake<ChevronRight size={18} /></button><small>Session setup is saved when live intake opens.</small></aside>
    </div>
  </div>
}
