import { AlertTriangle, ArrowLeft, CheckCircle2, CircleSlash, ExternalLink } from 'lucide-react'
import { useEffect } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Notice, PageHeader, Progress, StatusPill } from '../components/ui'
import { db } from '../lib/db'
import { isMetricValueValid, scoreAssessment } from '../lib/scoring'
import { useData } from '../lib/useData'
import { displayDate } from '../lib/utils'

export default function ReviewSessionPage() {
  const { sessionId } = useParams(); const { athletes, sessions, measurements, standards } = useData(); const session = sessions.find((s) => s.id === sessionId); const version = standards.find((s) => s.id === session?.standardsVersionId)
  useEffect(() => { if (session?.status === 'in_progress') void db.sessions.update(session.id, { status: 'review', updatedAt: new Date().toISOString() }) }, [session])
  if (!session || !version) return <div className="page"><Notice tone="warning">Session not found.</Notice></div>
  const roster = athletes.filter((a) => session.athleteIds.includes(a.id)); const results = measurements.filter((m) => m.sessionId === session.id); const expected = roster.length * session.metricIds.length; const problems = results.filter((measurement) => { const metric = version.metrics.find((item) => item.id === measurement.metricId); return measurement.status !== 'valid' || (metric && !isMetricValueValid(metric, measurement.selectedAttempt)) }); const valid = results.filter((m) => m.status === 'valid' && m.selectedAttempt !== null && !problems.some((problem) => problem.id === m.id)).length; const complete = roster.every((a) => scoreAssessment(version, results, a.id).complete) && problems.length === 0
  async function publish() { if (!complete || problems.length) return; await db.sessions.update(session!.id, { status: 'published', publishedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }) }
  return <div className="page"><Link className="back-link" to={`/testing/${session.id}/live`}><ArrowLeft size={16} />Live intake</Link><PageHeader eyebrow="Quality control" title="Review assessment" description={`${session.name} · ${displayDate(session.date)}`} actions={session.status === 'published' ? <StatusPill tone="good">Published</StatusPill> : <button className="button primary" disabled={!complete || problems.length > 0} onClick={publish}><CheckCircle2 size={18} />Approve and publish</button>} />
    <section className="review-summary"><div className="panel"><span>Completeness</span><strong>{valid} / {expected}</strong><Progress value={valid} max={expected} /><small>{expected - valid} required results remain</small></div><div className="panel"><span>Invalid results</span><strong>{problems.filter((p) => p.status === 'invalid').length}</strong><small>Resolve before publication</small></div><div className="panel"><span>Excluded results</span><strong>{problems.filter((p) => p.status === 'excluded').length}</strong><small>Excluded values do not score</small></div><div className="panel"><span>Standard</span><strong>v{version.version}</strong><small>{version.name}</small></div></section>
    {!complete && <Notice tone="warning"><strong>Publication is locked.</strong> Every athlete needs every required metric. Incomplete athletes keep an Incomplete label and never receive a fabricated total.</Notice>}
    {session.status === 'published' && <Notice tone="success"><strong>Published locally.</strong> Athlete reports now use these exact approved measurements and standards version {version.version}.</Notice>}
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Roster check</p><h2>Athlete completeness</h2></div><span>Every captured result can be validated, invalidated, or excluded.</span></div><div className="table-scroll"><table><thead><tr><th>Athlete</th>{version.metrics.map((m) => <th key={m.id}>{m.shortName}</th>)}<th>Overall</th><th>Report</th></tr></thead><tbody>{roster.map((athlete) => { const result = scoreAssessment(version, results, athlete.id); return <tr key={athlete.id}><td><strong>{athlete.firstName} {athlete.lastName}</strong><small>{athlete.group}</small></td>{version.metrics.map((metric) => { const measurement = results.find((m) => m.athleteId === athlete.id && m.metricId === metric.id); return <td key={metric.id}>{measurement?.selectedAttempt !== null && measurement?.selectedAttempt !== undefined ? <div className="review-result"><span className={measurement.status === 'valid' && isMetricValueValid(metric, measurement.selectedAttempt) ? 'valid-result' : 'invalid-result'}>{measurement.selectedAttempt} {metric.unit}</span><select aria-label={`${athlete.firstName} ${athlete.lastName} ${metric.name} status`} disabled={session.status === 'published'} value={measurement.status} onChange={(e) => db.measurements.update(measurement.id, { status: e.target.value as 'valid' | 'invalid' | 'excluded', updatedAt: new Date().toISOString() })}><option value="valid">Valid</option><option value="invalid">Invalid</option><option value="excluded">Excluded</option></select></div> : <span className="missing-result">Missing</span>}</td> })}<td><strong>{result.overall ?? 'Incomplete'}</strong></td><td><Link to={`/reporting/${athlete.id}`}>Open <ExternalLink size={13} /></Link></td></tr> })}</tbody></table></div></section>
    {problems.length > 0 && <section className="panel"><div className="section-heading"><div><p className="eyebrow">Exceptions</p><h2>Invalid or excluded results</h2></div><AlertTriangle /></div><div className="exception-list">{problems.map((item) => { const athlete = athletes.find((a) => a.id === item.athleteId); const metric = version.metrics.find((m) => m.id === item.metricId); return <div key={item.id}><CircleSlash /><div><strong>{athlete?.firstName} {athlete?.lastName} · {metric?.name}</strong><span>{item.selectedAttempt} {metric?.unit} · {item.status}</span></div><select disabled={session.status === 'published'} value={item.status} onChange={(e) => db.measurements.update(item.id, { status: e.target.value as 'valid' | 'invalid' | 'excluded', updatedAt: new Date().toISOString() })}><option value="valid">Valid</option><option value="invalid">Invalid</option><option value="excluded">Excluded</option></select></div> })}</div></section>}
  </div>
}
