import { Check, Cloud, Palette, RotateCcw, Shield, SunMoon, Upload, Users } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { BRAND_PRESETS, DEFAULT_BRAND, saveBrandSettings, useBrandSettings } from '../lib/branding'
import { DEFAULT_CLOUD_CONNECTION, LOCAL_DATA_PROVIDER } from '../lib/cloud'
import { imageFileToDataUrl } from '../lib/images'
import type { BrandSettings } from '../lib/types'
import { Notice, PageHeader, StatusPill } from '../components/ui'

export default function SettingsPage() {
  const current = useBrandSettings(); const [draft, setDraft] = useState<BrandSettings>(current); const [saved, setSaved] = useState(false); const logoInput = useRef<HTMLInputElement>(null)
  useEffect(() => setDraft(current), [current])
  async function save() { await saveBrandSettings(draft); setSaved(true); window.setTimeout(() => setSaved(false), 1800) }
  async function logo(file?: File) { if (!file) return; try { const logoDataUrl = await imageFileToDataUrl(file); setDraft((value) => ({ ...value, logoDataUrl })) } finally { if (logoInput.current) logoInput.current.value = '' } }
  return <div className="page settings-page"><PageHeader eyebrow="System configuration" title="Settings" description="Apply a coach's identity without changing assessment data, scoring contracts, or application plumbing." actions={<button className="button primary" onClick={save}><Check size={17} />{saved ? 'Saved' : 'Save branding'}</button>} />
    <Notice><strong>Brand safe by design.</strong> Colors, typography, names, and logo are stored separately from athlete and scoring records. A visual overhaul cannot change published results.</Notice>
    <div className="settings-layout"><section className="panel brand-settings"><div className="section-heading"><div><p className="eyebrow">Coach identity</p><h2>Brand system</h2></div><Palette /></div><div className="brand-preview" style={{ background: draft.inkColor, color: '#fff', borderColor: draft.primaryColor }}><span style={{ background: draft.accentColor }} />{draft.logoDataUrl && <img src={draft.logoDataUrl} alt="Logo preview" />}<div><strong style={{ fontFamily: draft.displayFont }}>{draft.organizationName}</strong><small>{draft.productName}</small></div></div><div className="settings-form"><label>Organization name<input value={draft.organizationName} onChange={(event) => setDraft({ ...draft, organizationName: event.target.value })} /></label><label>Product name<input value={draft.productName} onChange={(event) => setDraft({ ...draft, productName: event.target.value })} /></label><label>Primary color<input type="color" value={draft.primaryColor} onChange={(event) => setDraft({ ...draft, primaryColor: event.target.value })} /></label><label>Accent color<input type="color" value={draft.accentColor} onChange={(event) => setDraft({ ...draft, accentColor: event.target.value })} /></label><label>Shell color<input type="color" value={draft.inkColor} onChange={(event) => setDraft({ ...draft, inkColor: event.target.value })} /></label><label>Body font<select value={draft.bodyFont} onChange={(event) => setDraft({ ...draft, bodyFont: event.target.value })}><option>DM Sans</option><option>Arial</option><option>Verdana</option><option>system-ui</option></select></label><label>Display font<select value={draft.displayFont} onChange={(event) => setDraft({ ...draft, displayFont: event.target.value })}><option>Manrope</option><option>Arial</option><option>Arial Black</option><option>Georgia</option></select></label><label className="wide">Logo<input ref={logoInput} hidden type="file" accept="image/*" onChange={(event) => logo(event.target.files?.[0])} /><button className="button secondary" type="button" onClick={() => logoInput.current?.click()}><Upload size={16} />Choose image</button></label></div><div className="settings-actions"><button className="button secondary" onClick={() => setDraft(DEFAULT_BRAND)}><RotateCcw size={16} />Reset brand draft</button>{draft.logoDataUrl && <button className="button secondary" onClick={() => setDraft({ ...draft, logoDataUrl: undefined })}>Remove logo</button>}</div></section>
      <aside className="settings-side"><section className="panel"><p className="eyebrow">Design directions</p><h2>Fast visual concepts</h2><p>Apply a complete token set, then save. These presets affect the shell and reports without touching data.</p><div className="preset-list">{BRAND_PRESETS.map((preset) => <button key={preset.name} onClick={() => setDraft({ ...draft, ...preset.settings })}><span style={{ background: preset.settings.primaryColor }} /><div><strong>{preset.name}</strong><small>{preset.description}</small></div></button>)}</div><p className="agent-handoff">For a complete redesign, give <strong>DESIGN_AGENT_PROMPT.md</strong> to a coding agent. It requests multiple isolated concepts while preserving every data contract.</p></section></aside></div>
    <section className="settings-services"><article className="panel service-card"><Cloud /><div><span>Cloud database</span><h2>Supabase</h2><p>Provider status: {DEFAULT_CLOUD_CONNECTION.status.replace('_', ' ')}. The application routes persistence through a provider boundary so a future adapter can be added without changing scoring or reports.</p></div><StatusPill tone="warning">Not connected</StatusPill></article><article className="panel service-card"><Users /><div><span>Organization access</span><h2>Users and roles</h2><p>Single-device use is active. Cloud-backed authentication and role policies require an explicitly configured provider.</p></div><StatusPill tone="warning">Not configured</StatusPill></article><article className="panel service-card"><SunMoon /><div><span>Display preference</span><h2>Light and dark mode</h2><p>The light system and focused dark live-intake surface are active. User-selectable theme persistence is reserved for a future release.</p></div><StatusPill tone="warning">Not configured</StatusPill></article><article className="panel service-card"><Shield /><div><span>Active data provider</span><h2>Browser database</h2><p>{LOCAL_DATA_PROVIDER.athleteDataBoundary} IndexedDB persistence, JSON backup, CSV import, validation, and export are active now.</p></div><StatusPill tone="good">Connected</StatusPill></article></section>
  </div>
}
