import { ArrowDown, ArrowUp, Info, Plus, X } from 'lucide-react'
import { useState } from 'react'
import { Notice, PageHeader, StatusPill } from '../components/ui'
import { db } from '../lib/db'
import { latestStandardsVersion } from '../lib/report'
import { validateStandardsVersion } from '../lib/standards'
import type { Direction, StandardsVersion } from '../lib/types'
import { useData } from '../lib/useData'
import { displayDate, localISODate } from '../lib/utils'

const nextPatch = (value: string) => { const parts = value.split('.').map(Number); return parts.length === 3 && parts.every(Number.isFinite) ? `${parts[0]}.${parts[1]}.${parts[2] + 1}` : `${value}.1` }

export default function StandardsPage() {
  const { standards } = useData(); const latest = latestStandardsVersion(standards); const [selectedId, setSelectedId] = useState(''); const [draft, setDraft] = useState<StandardsVersion | null>(null); const [errors, setErrors] = useState<string[]>([]); const version = standards.find((item) => item.id === selectedId) ?? latest
  if (!version) return null
  function beginVersion() { if (!version) return; setErrors([]); setDraft({ ...structuredClone(version), id: crypto.randomUUID(), version: nextPatch(version.version), effectiveDate: localISODate(), name: `${version.name.replace(/ · Revision.*$/, '')} · Revision`, description: `${version.description} Created from version ${version.version}.` }) }
  function updateMetric(index: number, field: string, value: string | number | boolean) { if (!draft) return; const metrics = structuredClone(draft.metrics); metrics[index] = { ...metrics[index], [field]: value }; setDraft({ ...draft, metrics }) }
  function updateBand(metricIndex: number, bandIndex: number, field: string, value: string | number | undefined) { if (!draft) return; const metrics = structuredClone(draft.metrics); metrics[metricIndex].bands[bandIndex] = { ...metrics[metricIndex].bands[bandIndex], [field]: value }; setDraft({ ...draft, metrics }) }
  async function saveVersion() { if (!draft) return; const nextErrors = validateStandardsVersion(draft); if (standards.some((item) => item.version === draft.version)) nextErrors.push(`Version ${draft.version} already exists.`); if (nextErrors.length) { setErrors(nextErrors); return } await db.standards.add(draft); setSelectedId(draft.id); setDraft(null); setErrors([]) }
  return <div className="page"><PageHeader eyebrow="Scoring contract" title="Standards" description="Inspect and version the exact metrics, validation ranges, directions, weights, and five scoring bands." actions={<><select aria-label="Displayed standards version" value={version.id} onChange={(event) => setSelectedId(event.target.value)}>{[...standards].sort((a, b) => b.effectiveDate.localeCompare(a.effectiveDate)).map((item) => <option key={item.id} value={item.id}>v{item.version} · {item.name}</option>)}</select><button className="button primary" onClick={beginVersion}><Plus size={17} />Create version</button></>} />
    <Notice tone="warning"><strong>Not validated population norms.</strong> These synthetic bands create a coherent working example. A qualified coach must replace and version them before making population claims or consequential decisions.</Notice>
    <section className="standards-summary panel"><div><span>Standard</span><strong>{version.name}</strong></div><div><span>Version</span><strong>{version.version}</strong></div><div><span>Effective</span><strong>{displayDate(version.effectiveDate)}</strong></div><div><span>Required score weight</span><strong>{version.metrics.reduce((sum, m) => sum + m.weight, 0)}%</strong></div></section>
    <section className="standards-list">{version.metrics.map((metric) => <article className="panel standard-card" key={metric.id}><header><div><div className="metric-title"><h2>{metric.name}</h2><StatusPill>{metric.required ? 'Required' : 'Optional'}</StatusPill></div><p>{metric.percentileContext}</p></div><div className="direction-card">{metric.direction === 'higher' ? <ArrowUp /> : <ArrowDown />}<span>{metric.direction === 'higher' ? 'Higher is better' : 'Lower is better'}</span><strong>{metric.weight}% weight · {metric.validMin} to {metric.validMax} {metric.unit}</strong></div></header><div className="band-grid">{metric.bands.map((band, index) => <div key={band.label} style={{ borderTopColor: band.color }}><span>Band {index + 1}</span><strong>{band.label}</strong><b>{band.points} points</b><small>{band.min === undefined ? `< ${band.max}` : band.max === undefined ? `≥ ${band.min}` : `${band.min} to < ${band.max}`} {metric.unit}</small><p>{band.meaning}</p></div>)}</div></article>)}</section>
    <section className="panel incomplete-contract"><Info /><div><p className="eyebrow">Incomplete score contract</p><h2>Missing means Incomplete</h2><p>If any required metric is absent, invalid, or excluded, the application returns no overall score. It does not substitute averages, allocate missing weight, or combine measurements from another athlete. Every completed score carries the exact version attached to its published session.</p></div></section>
    {draft && <div className="modal-backdrop"><div className="modal standards-modal" role="dialog" aria-modal="true" aria-labelledby="standards-editor-title"><div className="modal-header"><div><p className="eyebrow">Append-only standards</p><h2 id="standards-editor-title">Create scoring version</h2></div><button className="icon-button" aria-label="Close standards editor" onClick={() => setDraft(null)}><X /></button></div>
      <Notice>Saving creates a new immutable version. Existing sessions and reports remain attached to their original version.</Notice>{errors.map((error) => <Notice key={error} tone="warning">{error}</Notice>)}
      <div className="form-grid standards-meta"><label>Version<input aria-label="New standard version" value={draft.version} onChange={(event) => setDraft({ ...draft, version: event.target.value })} /></label><label>Effective date<input type="date" value={draft.effectiveDate} onChange={(event) => setDraft({ ...draft, effectiveDate: event.target.value })} /></label><label className="wide">Standard name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label></div>
      <div className="standards-editor-list">{draft.metrics.map((metric, metricIndex) => <section key={metric.id} className="editor-metric"><h3>{metric.name}</h3><div className="editor-metric-grid"><label>Name<input value={metric.name} onChange={(event) => updateMetric(metricIndex, 'name', event.target.value)} /></label><label>Unit<input value={metric.unit} onChange={(event) => updateMetric(metricIndex, 'unit', event.target.value)} /></label><label>Direction<select value={metric.direction} onChange={(event) => updateMetric(metricIndex, 'direction', event.target.value as Direction)}><option value="higher">Higher is better</option><option value="lower">Lower is better</option></select></label><label>Weight %<input type="number" value={metric.weight} onChange={(event) => updateMetric(metricIndex, 'weight', Number(event.target.value))} /></label><label>Valid minimum<input type="number" step="any" value={metric.validMin} onChange={(event) => updateMetric(metricIndex, 'validMin', Number(event.target.value))} /></label><label>Valid maximum<input type="number" step="any" value={metric.validMax} onChange={(event) => updateMetric(metricIndex, 'validMax', Number(event.target.value))} /></label></div><div className="editor-bands">{metric.bands.map((band, bandIndex) => <div key={`${metric.id}-${bandIndex}`}><label>Label<input value={band.label} onChange={(event) => updateBand(metricIndex, bandIndex, 'label', event.target.value)} /></label><label>Minimum<input type="number" step="any" placeholder="Open" value={band.min ?? ''} onChange={(event) => updateBand(metricIndex, bandIndex, 'min', event.target.value === '' ? undefined : Number(event.target.value))} /></label><label>Maximum<input type="number" step="any" placeholder="Open" value={band.max ?? ''} onChange={(event) => updateBand(metricIndex, bandIndex, 'max', event.target.value === '' ? undefined : Number(event.target.value))} /></label><label>Points<input type="number" value={band.points} onChange={(event) => updateBand(metricIndex, bandIndex, 'points', Number(event.target.value))} /></label><label className="meaning">Meaning<input value={band.meaning} onChange={(event) => updateBand(metricIndex, bandIndex, 'meaning', event.target.value)} /></label></div>)}</div></section>)}</div><div className="modal-actions"><button className="button secondary" onClick={() => setDraft(null)}>Cancel</button><button className="button primary" onClick={saveVersion}>Save new version</button></div>
    </div></div>}
  </div>
}
