import { ArrowDown, ArrowUp, CopyPlus, Info, Plus, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Notice, PageHeader, StatusPill } from '../components/ui'
import { db } from '../lib/db'
import { latestStandardsVersion } from '../lib/report'
import { bandsForMetric, validateStandardsVersion } from '../lib/standards'
import type { AthleteSex, Direction, StandardsAudience, StandardsProfile, StandardsVersion } from '../lib/types'
import { useData } from '../lib/useData'
import { localISODate } from '../lib/utils'

const nextPatch = (value: string) => { const parts = value.split('.').map(Number); return parts.length === 3 && parts.every(Number.isFinite) ? `${parts[0]}.${parts[1]}.${parts[2] + 1}` : `${value}.1` }
const splitList = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean)
const audienceSummary = (profile: StandardsProfile) => {
  const parts = [profile.audience.sexes.length ? profile.audience.sexes.join(' or ') : '', profile.audience.ageMin !== undefined || profile.audience.ageMax !== undefined ? `ages ${profile.audience.ageMin ?? 'open'} to ${profile.audience.ageMax ?? 'open'}` : '', profile.audience.grades.length ? `grades ${profile.audience.grades.join(', ')}` : '', profile.audience.sports.length ? profile.audience.sports.join(', ') : '', profile.audience.positions.length ? profile.audience.positions.join(', ') : ''].filter(Boolean)
  return parts.length ? parts.join(' · ') : 'All athletes. Required fallback profile.'
}

export default function StandardsPage() {
  const { standards } = useData(); const latest = latestStandardsVersion(standards); const [selectedId, setSelectedId] = useState(''); const [selectedProfileId, setSelectedProfileId] = useState(''); const [draft, setDraft] = useState<StandardsVersion | null>(null); const [draftProfileId, setDraftProfileId] = useState(''); const [errors, setErrors] = useState<string[]>([]); const version = standards.find((item) => item.id === selectedId) ?? latest
  const profile = version?.profiles.find((item) => item.id === selectedProfileId) ?? version?.profiles[0]
  const draftProfile = draft?.profiles.find((item) => item.id === draftProfileId) ?? draft?.profiles[0]
  useEffect(() => { if (version && !version.profiles.some((item) => item.id === selectedProfileId)) setSelectedProfileId(version.profiles[0]?.id ?? '') }, [selectedProfileId, version])
  if (!version || !profile) return null

  function beginVersion() { if (!version) return; const next: StandardsVersion = { ...structuredClone(version), id: crypto.randomUUID(), version: nextPatch(version.version), effectiveDate: localISODate(), name: `${version.name.replace(/ · Revision.*$/, '')} · Revision`, description: `${version.description} Created from version ${version.version}.` }; setErrors([]); setDraft(next); setDraftProfileId(next.profiles[0]?.id ?? '') }
  function updateMetric(index: number, field: string, value: string | number | boolean) { if (!draft) return; const metrics = structuredClone(draft.metrics); metrics[index] = { ...metrics[index], [field]: value }; setDraft({ ...draft, metrics }) }
  function updateBand(metricIndex: number, bandIndex: number, field: string, value: string | number | undefined) { if (!draft || !draftProfile) return; const profiles = structuredClone(draft.profiles); const profileIndex = profiles.findIndex((item) => item.id === draftProfile.id); const metric = draft.metrics[metricIndex]; const bands = structuredClone(bandsForMetric(profiles[profileIndex], metric.id, metric.bands)); bands[bandIndex] = { ...bands[bandIndex], [field]: value }; profiles[profileIndex].bandsByMetric[metric.id] = bands; setDraft({ ...draft, profiles }) }
  function updateProfile(field: 'name' | 'priority', value: string | number) { if (!draft || !draftProfile) return; setDraft({ ...draft, profiles: draft.profiles.map((item) => item.id === draftProfile.id ? { ...item, [field]: value } : item) }) }
  function updateAudience(patch: Partial<StandardsAudience>) { if (!draft || !draftProfile) return; setDraft({ ...draft, profiles: draft.profiles.map((item) => item.id === draftProfile.id ? { ...item, audience: { ...item.audience, ...patch } } : item) }) }
  function addProfile() { if (!draft || !draftProfile) return; const id = crypto.randomUUID(); const next: StandardsProfile = { id, name: 'New audience profile', priority: draft.profiles.length * 10, audience: { sexes: [], grades: [], sports: [], positions: [] }, bandsByMetric: structuredClone(draftProfile.bandsByMetric) }; setDraft({ ...draft, profiles: [...draft.profiles, next] }); setDraftProfileId(id) }
  async function saveVersion() { if (!draft) return; const nextErrors = validateStandardsVersion(draft); if (standards.some((item) => item.version === draft.version)) nextErrors.push(`Version ${draft.version} already exists.`); if (nextErrors.length) { setErrors(nextErrors); return } await db.standards.add(draft); setSelectedId(draft.id); setSelectedProfileId(draft.profiles[0].id); setDraft(null); setErrors([]) }

  return <div className="page"><PageHeader eyebrow="Scoring contract" title="Standards" description="Version each battery and define which standards profile applies by sex, age, grade, sport, or position." actions={<><select aria-label="Displayed standards version" value={version.id} onChange={(event) => setSelectedId(event.target.value)}>{[...standards].sort((a, b) => b.effectiveDate.localeCompare(a.effectiveDate)).map((item) => <option key={item.id} value={item.id}>v{item.version} · {item.name}</option>)}</select><button className="button primary" onClick={beginVersion}><Plus size={17} />Create version</button></>} />
    <Notice tone="warning"><strong>Editable starter standards.</strong> The included audience profiles demonstrate matching and versioning. Their bands are synthetic and are not validated population norms.</Notice>
    <section className="standards-summary panel"><div><span>Battery</span><strong>{version.name}</strong></div><div><span>Version</span><strong>{version.version}</strong></div><div><span>Audience profiles</span><strong>{version.profiles.length}</strong></div><div><span>Maximum point total</span><strong>{version.metrics.length * 4}</strong></div></section>
    <section className="profile-switcher panel"><div><p className="eyebrow">Audience standards</p><h2>Scoring profiles inside this battery</h2><p>The highest priority matching profile grades each athlete. The general profile catches every athlete who does not match a narrower rule.</p></div><div className="profile-tabs">{version.profiles.map((item) => <button className={item.id === profile.id ? 'active' : ''} key={item.id} onClick={() => setSelectedProfileId(item.id)}><strong>{item.name}</strong><span>{audienceSummary(item)}</span></button>)}</div><div className="profile-readout"><span>Active view</span><strong>{profile.name}</strong><small>{audienceSummary(profile)} · Priority {profile.priority}</small></div></section>
    <section className="standards-list">{version.metrics.map((metric) => { const bands = bandsForMetric(profile, metric.id, metric.bands); return <article className="panel standard-card" key={metric.id}><header><div><div className="metric-title"><h2>{metric.name}</h2><StatusPill>{metric.required ? 'Required' : 'Optional'}</StatusPill></div><p>{metric.percentileContext}</p></div><div className="direction-card">{metric.direction === 'higher' ? <ArrowUp /> : <ArrowDown />}<span>{metric.direction === 'higher' ? 'Higher is better' : 'Lower is better'}</span><strong>{metric.weight}% weight · {metric.validMin} to {metric.validMax} {metric.unit}</strong></div></header><div className="band-grid">{bands.map((band) => <div key={`${profile.id}-${band.label}`} style={{ borderTopColor: band.color }}><span>Grade {band.points}</span><strong>{band.label}</strong><b>{band.points} point{band.points === 1 ? '' : 's'}</b><small>{band.min === undefined ? `< ${band.max}` : band.max === undefined ? `≥ ${band.min}` : `${band.min} to < ${band.max}`} {metric.unit}</small><p>{band.meaning}</p></div>)}</div></article> })}</section>
    <section className="panel incomplete-contract"><Info /><div><p className="eyebrow">Point-total contract</p><h2>Five tests, zero to four points each</h2><p>A complete athlete total is the sum of every metric grade. If a required result is missing, invalid, or excluded, the point total remains Incomplete. No averages, missing-weight allocation, or cross-athlete substitution are allowed.</p></div></section>

    {draft && draftProfile && <div className="modal-backdrop"><div className="modal standards-modal" role="dialog" aria-modal="true" aria-labelledby="standards-editor-title"><div className="modal-header"><div><p className="eyebrow">Append-only scoring contract</p><h2 id="standards-editor-title">Create standards version</h2><p>Configure the battery once, then create targeted audience profiles inside it.</p></div><button className="icon-button" aria-label="Close standards editor" onClick={() => setDraft(null)}><X /></button></div>
      <Notice>Saving creates a new immutable version. Existing sessions and reports remain attached to their original version and profile resolution.</Notice>{errors.map((error) => <Notice key={error} tone="warning">{error}</Notice>)}
      <div className="form-grid standards-meta"><label>Version<input aria-label="New standard version" value={draft.version} onChange={(event) => setDraft({ ...draft, version: event.target.value })} /></label><label>Effective date<input type="date" value={draft.effectiveDate} onChange={(event) => setDraft({ ...draft, effectiveDate: event.target.value })} /></label><label className="wide">Battery name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label></div>
      <section className="audience-editor"><div className="audience-nav"><div><p className="eyebrow">Standards profiles</p><h3>Who is being graded?</h3></div>{draft.profiles.map((item) => <button className={item.id === draftProfile.id ? 'active' : ''} key={item.id} onClick={() => setDraftProfileId(item.id)}><strong>{item.name}</strong><span>{audienceSummary(item)}</span></button>)}<button className="add-profile" onClick={addProfile}><CopyPlus size={15} />Add standards profile</button></div><div className="audience-fields"><div className="section-heading"><div><p className="eyebrow">Matching rules</p><h2>{draftProfile.name}</h2></div><StatusPill>Priority {draftProfile.priority}</StatusPill></div><div className="audience-grid"><label>Profile name<input value={draftProfile.name} onChange={(event) => updateProfile('name', event.target.value)} /></label><label>Priority<input type="number" value={draftProfile.priority} onChange={(event) => updateProfile('priority', Number(event.target.value))} /></label><label>Sex<select aria-label="Profile sex" value={draftProfile.audience.sexes[0] ?? 'any'} onChange={(event) => updateAudience({ sexes: event.target.value === 'any' ? [] : [event.target.value as AthleteSex] })}><option value="any">Any sex</option><option value="female">Female</option><option value="male">Male</option></select></label><label>Minimum age<input type="number" placeholder="Open" value={draftProfile.audience.ageMin ?? ''} onChange={(event) => updateAudience({ ageMin: event.target.value === '' ? undefined : Number(event.target.value) })} /></label><label>Maximum age<input type="number" placeholder="Open" value={draftProfile.audience.ageMax ?? ''} onChange={(event) => updateAudience({ ageMax: event.target.value === '' ? undefined : Number(event.target.value) })} /></label><label>Grades<input placeholder="9, 10, 11" value={draftProfile.audience.grades.join(', ')} onChange={(event) => updateAudience({ grades: splitList(event.target.value) })} /></label><label>Sports<input placeholder="Football, Soccer" value={draftProfile.audience.sports.join(', ')} onChange={(event) => updateAudience({ sports: splitList(event.target.value) })} /></label><label>Positions<input placeholder="Linebacker, Guard" value={draftProfile.audience.positions.join(', ')} onChange={(event) => updateAudience({ positions: splitList(event.target.value) })} /></label></div><p className="field-help">Blank rules match everyone. Use a higher priority when two profiles could match the same athlete.</p></div></section>
      <div className="standards-editor-list">{draft.metrics.map((metric, metricIndex) => { const bands = bandsForMetric(draftProfile, metric.id, metric.bands); return <section key={metric.id} className="editor-metric"><div className="editor-metric-heading"><div><p className="eyebrow">{draftProfile.name}</p><h3>{metric.name}</h3></div><span>Grades must remain 0, 1, 2, 3, 4</span></div><div className="editor-metric-grid"><label>Name<input value={metric.name} onChange={(event) => updateMetric(metricIndex, 'name', event.target.value)} /></label><label>Unit<input value={metric.unit} onChange={(event) => updateMetric(metricIndex, 'unit', event.target.value)} /></label><label>Direction<select value={metric.direction} onChange={(event) => updateMetric(metricIndex, 'direction', event.target.value as Direction)}><option value="higher">Higher is better</option><option value="lower">Lower is better</option></select></label><label>Weight %<input type="number" value={metric.weight} onChange={(event) => updateMetric(metricIndex, 'weight', Number(event.target.value))} /></label><label>Valid minimum<input type="number" step="any" value={metric.validMin} onChange={(event) => updateMetric(metricIndex, 'validMin', Number(event.target.value))} /></label><label>Valid maximum<input type="number" step="any" value={metric.validMax} onChange={(event) => updateMetric(metricIndex, 'validMax', Number(event.target.value))} /></label></div><div className="editor-bands">{bands.map((band, bandIndex) => <div key={`${metric.id}-${bandIndex}`}><label>Grade<input type="number" min="0" max="4" value={band.points} onChange={(event) => updateBand(metricIndex, bandIndex, 'points', Number(event.target.value))} /></label><label>Label<input value={band.label} onChange={(event) => updateBand(metricIndex, bandIndex, 'label', event.target.value)} /></label><label>Minimum<input type="number" step="any" placeholder="Open" value={band.min ?? ''} onChange={(event) => updateBand(metricIndex, bandIndex, 'min', event.target.value === '' ? undefined : Number(event.target.value))} /></label><label>Maximum<input type="number" step="any" placeholder="Open" value={band.max ?? ''} onChange={(event) => updateBand(metricIndex, bandIndex, 'max', event.target.value === '' ? undefined : Number(event.target.value))} /></label><label className="meaning">Meaning<input value={band.meaning} onChange={(event) => updateBand(metricIndex, bandIndex, 'meaning', event.target.value)} /></label></div>)}</div></section> })}</div><div className="modal-actions"><button className="button secondary" onClick={() => setDraft(null)}>Cancel</button><button className="button primary" onClick={saveVersion}>Save new version</button></div>
    </div></div>}
  </div>
}
