import { Pencil, Plus, X } from 'lucide-react'
import { useState } from 'react'
import { archetypeDescription, matchesArchetype } from '../lib/archetypes'
import { db } from '../lib/db'
import type { Athlete, ComparisonArchetype } from '../lib/types'
import { localISODate } from '../lib/utils'
import { StatusPill } from './ui'

const blank = (): ComparisonArchetype => ({ id: crypto.randomUUID(), name: '', active: true, priority: 10, sexes: [], sports: [], positions: [], grades: [], levels: [], createdAt: new Date().toISOString() })
export default function ArchetypeManager({ archetypes, athletes }: { archetypes: ComparisonArchetype[]; athletes: Athlete[] }) {
  const [draft, setDraft] = useState<ComparisonArchetype | null>(null); const [error, setError] = useState('')
  async function save() { if (!draft?.name.trim()) { setError('Name is required.'); return } if (draft.ageMin !== undefined && draft.ageMax !== undefined && draft.ageMin > draft.ageMax) { setError('Minimum age cannot exceed maximum age.'); return } await db.archetypes.put({ ...draft, name: draft.name.trim() }); setDraft(null); setError('') }
  return <section className="panel archetype-manager" id="archetypes"><div className="section-heading"><div><p className="eyebrow">Percentile cohorts</p><h2>Comparison archetypes</h2><p>Define the athlete tags that determine percentile peers. Age, sex, and sport are the core fields. Position, grade, and level add optional precision. When an athlete matches more than one archetype, the highest priority and then the most specific definition wins.</p></div><button className="button primary" onClick={() => setDraft(blank())}><Plus size={16} />New archetype</button></div><div className="archetype-records">{archetypes.map((item) => { const members = athletes.filter((athlete) => matchesArchetype(item, athlete, localISODate())); return <article key={item.id}><div><div className="archetype-record-title"><h3>{item.name}</h3><StatusPill tone={item.active ? 'good' : 'neutral'}>{item.active ? 'Active' : 'Inactive'}</StatusPill></div><p>{archetypeDescription(item)}</p></div><div className="archetype-record-count"><strong>{members.length}</strong><span>current matches</span></div><button className="button secondary" onClick={() => setDraft(structuredClone(item))}><Pencil size={15} />Edit</button></article> })}</div>
    {draft && <div className="modal-backdrop"><div className="modal archetype-modal" role="dialog" aria-modal="true" aria-labelledby="archetype-title"><div className="modal-header"><div><p className="eyebrow">Database comparison group</p><h2 id="archetype-title">{archetypes.some((item) => item.id === draft.id) ? 'Edit archetype' : 'New archetype'}</h2></div><button className="icon-button" aria-label="Close archetype editor" onClick={() => setDraft(null)}><X /></button></div>{error && <p className="validation-error" role="alert">{error}</p>}<div className="form-grid"><label className="wide">Name<input aria-label="Archetype name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Example: Female soccer · ages 16–18" /></label><label>Minimum age<input aria-label="Archetype minimum age" type="number" value={draft.ageMin ?? ''} onChange={(event) => setDraft({ ...draft, ageMin: event.target.value ? Number(event.target.value) : undefined })} /></label><label>Maximum age<input aria-label="Archetype maximum age" type="number" value={draft.ageMax ?? ''} onChange={(event) => setDraft({ ...draft, ageMax: event.target.value ? Number(event.target.value) : undefined })} /></label><label>Sex<select aria-label="Archetype sex" value={draft.sexes[0] ?? ''} onChange={(event) => setDraft({ ...draft, sexes: event.target.value ? [event.target.value as ComparisonArchetype['sexes'][number]] : [] })}><option value="">Any sex</option><option value="female">Female</option><option value="male">Male</option><option value="unspecified">Unspecified</option></select></label><label>Priority<input aria-label="Archetype priority" type="number" value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: Number(event.target.value) })} /></label><TagField label="Sports" value={draft.sports} set={(sports) => setDraft({ ...draft, sports })} placeholder="Soccer, Basketball" /><TagField label="Positions" value={draft.positions} set={(positions) => setDraft({ ...draft, positions })} placeholder="Guard, Midfielder" /><TagField label="Grades" value={draft.grades} set={(grades) => setDraft({ ...draft, grades })} placeholder="10, 11, 12" /><TagField label="Levels" value={draft.levels} set={(levels) => setDraft({ ...draft, levels })} placeholder="Varsity, Development" /><label className="wide archetype-active"><input type="checkbox" checked={draft.active} onChange={(event) => setDraft({ ...draft, active: event.target.checked })} />Active for reports and rankings</label></div><div className="modal-actions"><button className="button secondary" onClick={() => setDraft(null)}>Cancel</button><button className="button primary" onClick={save}>Save archetype</button></div></div></div>}
  </section>
}

function TagField({ label, value, set, placeholder }: { label: string; value: string[]; set: (value: string[]) => void; placeholder: string }) { return <label>{label}<input aria-label={`Archetype ${label.toLowerCase()}`} value={value.join(', ')} onChange={(event) => set(event.target.value.split(',').map((item) => item.trim()).filter(Boolean))} placeholder={placeholder} /></label> }
